apiVersion: v1
kind: Service
metadata:
  labels:
    service: spring-backend
  name: spring-backend
spec:
  type: NodePort
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    service: spring-backend

